name: Daily Water Level Notification

on:
  schedule:
    # 07:30 ICT → 00:30 UTC
    - cron: '30 0 * * *'
    # 16:00 ICT → 09:00 UTC
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      # ▼▼▼ การแก้ไขทั้งหมดอยู่ตรงนี้ ▼▼▼
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          # บังคับให้ Job ที่รันตามเวลาได้รับสิทธิ์สูงสุดในการทำงาน
          # โดยใช้ Personal Access Token (PAT) ที่เราจะสร้างกัน
          token: ${{ secrets.PAT_TOKEN }}
      # ▲▲▲ การแก้ไขทั้งหมดอยู่ตรงนี้ ▲▲▲

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz pandas beautifulsoup4 selenium webdriver-manager openpyxl

      - name: Run Python script
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        run: python main.py
