name: Daily Water Level Notification

on:
  schedule:
    # 07:30 ICT -> 00:30 UTC
    - cron: '30 0 * * *'
    # 16:00 ICT -> 09:00 UTC
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz pandas beautifulsoup4 selenium webdriver-manager openpyxl

      - name: Run Python script
        env:
          # --- [แก้ไข] เปลี่ยนมาใช้ Secret ของ Make.com Webhook ---
          MAKE_WEBHOOK_URL: ${{ secrets.MAKE_WEBHOOK_URL }}
        run: python main.py
