name: notify

on:
  schedule:
    - cron: '30 0 * * *'   # 07:30 ไทย
    - cron: '30 9 * * *'   # 16:30 ไทย
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # ติดตั้ง library ที่จำเป็นสำหรับ Chrome/Selenium
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libfontconfig1

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Python Script
        run: python main.py
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
