name: Daily Water Level Notification

# By default, GitHub Actions runs cron jobs in UTC. To schedule this workflow to
# run at 07:30 and 16:00 every day in Thailand (Asia/Bangkok, UTC+07), convert those
# times to UTC (00:30 and 09:00). See GitHub docs for details on cron schedules.
# The workflow file must live in the `.github/workflows` directory for GitHub to
# detect and run it【669439309477516†L361-L408】.
on:
  schedule:
    # 07:30 ICT -> 00:30 UTC
    - cron: '30 0 * * *'
    # 16:00 ICT -> 09:00 UTC
    - cron: '0 9 * * *'
  # Allows you to manually run this workflow from the Actions tab.
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          # Use a Personal Access Token (PAT) to avoid permission issues when checking out
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz pandas beautifulsoup4 selenium webdriver-manager openpyxl

      - name: Run Python script
        env:
          # Provide your LINE channel access token via repository secrets
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        run: python main.py
