name: notify

on:
  schedule:
    - cron: '30 0 * * *'   # 07:30 ไทย
    - cron: '30 9 * * *'   # 16:30 ไทย
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # --- ส่วนที่เพิ่มเข้ามา ---
      # ติดตั้ง Google Chrome และ ChromeDriver ที่เข้ากันได้
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Python Script
        run: python main.py
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
