# ชื่อของ Workflow
name: Send Daily Water Level Notification

on:
  schedule:
    # ทำงานทุกวันเวลา 07:30 และ 16:30 ตามเวลาประเทศไทย (UTC+7)
    - cron: '30 0,9 * * *'
  # อนุญาตให้กดรันเองได้เพื่อการทดสอบ
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # === จุดที่แก้ไข ===
      # แก้ไขให้ติดตั้ง ChromeDriver ด้วย (โดยการลบบรรทัด 'install-chromedriver: false' ออก)
      # หรือจะกำหนดเป็น true ให้ชัดเจนก็ได้
      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        # Action นี้จะติดตั้งทั้งเบราว์เซอร์และไดรเวอร์เวอร์ชันที่ตรงกันให้โดยอัตโนมัติ

      - name: Run Python script
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        run: python main.py
